version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8

    commands:
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
      - export NVM_DIR="$HOME/.nvm"
      - [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      - nvm install 14

  build:
    commands:
      - npm install
      - npm run-script build

artifacts:
  files:
    - public/**/*
    - src/**/*
    - package.json
    - server.js
    - appspec.yml
    - scripts/**/*
























