version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11

    commands:
      - npm install

  build:
    commands:
      - npm run-script build

artifacts:
  files:
    - public/**/*
    - src/**/*
    - package.json
    - server.js
    - appspec.yml
    - scripts/**/*

