version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8

    commands:
      - curl -sL https://deb.nodesource.com/setup_14.x | bash -
      - apt-get install -y nodejs

  build:
    commands:
      - npm install
      - npm run-script build

artifacts:
  files:
    - public/**/*
    - src/**/*
    - package.json
    - server.js
    - appspec.yml
    - scripts/**/*

